/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const ProductID = IDL.Text;
export const Listing = IDL.Record({
  'id' : ProductID,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const SellerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'listings' : IDL.Vec(Listing),
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func([ListingInput], [ProductID], []),
  'createSellerProfile' : IDL.Func([IDL.Text], [], []),
  'deactivateListing' : IDL.Func([ProductID], [], []),
  'getAllSellers' : IDL.Func([], [IDL.Vec(SellerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([ProductID], [IDL.Opt(Listing)], ['query']),
  'getListingsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getMarketplaceWebpage' : IDL.Func([], [IDL.Text], ['query']),
  'getSellerProfile' : IDL.Func([IDL.Principal], [SellerProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSeller' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateListing' : IDL.Func([ProductID, ListingInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const ProductID = IDL.Text;
  const Listing = IDL.Record({
    'id' : ProductID,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const SellerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'listings' : IDL.Vec(Listing),
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func([ListingInput], [ProductID], []),
    'createSellerProfile' : IDL.Func([IDL.Text], [], []),
    'deactivateListing' : IDL.Func([ProductID], [], []),
    'getAllSellers' : IDL.Func([], [IDL.Vec(SellerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([ProductID], [IDL.Opt(Listing)], ['query']),
    'getListingsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getMarketplaceWebpage' : IDL.Func([], [IDL.Text], ['query']),
    'getSellerProfile' : IDL.Func([IDL.Principal], [SellerProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSeller' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateListing' : IDL.Func([ProductID, ListingInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };